  weighttracker-backend:
    container_name: weighttracker-backend
    restart: always
    image: weighttracker-backend
    logging:
      options:
        max-size: "5m"
        max-file: "3"      
    build:
        context: ../mounts/websites/weighttracker/
    tty: true
    ports:
      - 8000:8000   
    volumes:
      - ../mounts/websites/weighttracker:/opt/weighttracker.zz50.co.uk
      - ../backups/weighttrackerk:/mnt/backups
    depends_on:
      - postgres12
      - nginx
    external_links:
      - postgres12:postgres
    working_dir: /opt/weighttracker.zz50.co.uk/
    entrypoint: ['bash', '-c', './bin/start_container.sh']
    environment:
      - DB_NAME=weight_tracker  
      - DB_USERNAME=weight_tracker  
      - DB_PASSWORD=weight_tracker
      - DB_HOST=postgres
      - ENVIRONMENT=##ENVIRONMENT##
      - CONTAINER_TYPE=BACKEND

  weighttracker-frontend:
      container_name: weighttracker-frontend
      restart: always
      image: node:21-alpine3.17
      logging:
        options:
          max-size: "5m"
          max-file: "3"      
      tty: true
      ports:
        - 5123:5123   
      volumes:
        - ../mounts/websites/weighttracker:/opt/weighttracker.zz50.co.uk
      depends_on:
        - nginx
      working_dir: /opt/weighttracker.zz50.co.uk/
      entrypoint: ['sh', '-c', './bin/start_container.sh']
      environment:
        - ENVIRONMENT=##ENVIRONMENT##      
        - CONTAINER_TYPE=FRONTEND

      