weighttracker-backend:
  container_name: weighttracker-backend
  restart: always
  image: weighttracker-backend
  logging:
    options:
      max-size: "5m"
      max-file: "3"
  build:
    context: ../mounts/websites/weighttracker/backend
  tty: true
  ports:
    - 8000:8000
  depends_on:
    - postgres
    - nginx
  external_links:
    - postgres:postgres
  working_dir: /opt/weighttracker.zz50.co.uk/
  environment:
    - DB_NAME=${WEIGHT_TRACKER_DATABASE_NAME}
    - DB_USERNAME=${WEIGHT_TRACKER_DATABASE_USERNAME}
    - DB_PASSWORD=${WEIGHT_TRACKER_DATABASE_PASSWORD}
    - DB_HOST=postgres
    - ENVIRONMENT=${BLTA_ENVIRONMENT}
    - CONTAINER_TYPE=BACKEND
    - GOOGLE_OAUTH2_CLIENT_ID=${WEIGHT_TRACKER_GOOGLE_OAUTH2_CLIENT_ID}
    - GOOGLE_OAUTH2_CLIENT_SECRET=${WEIGHT_TRACKER_GOOGLE_OAUTH2_CLIENT_SECRET}

weighttracker-frontend:
  container_name: weighttracker-frontend
  restart: always
  image: node:21-alpine3.17
  logging:
    options:
      max-size: "5m"
      max-file: "3"
  tty: true
  ports:
    - 5123:5123
  volumes:
    - ../mounts/websites/weighttracker/frontend:/opt/weighttracker.zz50.co.uk
  depends_on:
    - nginx
  working_dir: /opt/weighttracker.zz50.co.uk/
  entrypoint: ["sh", "-c", "./bin/start_container.sh"]
  environment:
    - ENVIRONMENT=${BLTA_ENVIRONMENT}
    - CONTAINER_TYPE=FRONTEND
