_weighttracker:
    path:      /
    defaults:  { _controller: weighttrackerBundle:Default:index }

_register:
    path: /register
    defaults:  { _controller: weighttrackerBundle:Default:register }