_weighttracker:
    path:      /
    defaults:  { _controller: weighttrackerBundle:Default:index }

_register:
    path: /register
    defaults:  { _controller: weighttrackerBundle:Default:register }
    requirements:
      _method: POST

_weight:
    path: /weight
    defaults:  { _controller: weighttrackerBundle:Default:weight }