# Generated by Django 5.0.6 on 2024-06-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authentication_method',
            field=models.CharField(choices=[('google', 'Google')], default='google', max_length=6),
            preserve_default=False,
        ),
    ]
