# Generated by Django 5.0.6 on 2024-06-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_authentication_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='starting_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='target_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
