# Generated by Django 5.1.4 on 2025-01-02 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='week_weight_change_kg',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(limit_value=-6), django.core.validators.MaxValueValidator(limit_value=6)]),
        ),
        migrations.AlterField(
            model_name='weight',
            name='week_weight_change_percentage',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(limit_value=-3), django.core.validators.MaxValueValidator(limit_value=3)]),
        ),
    ]
