# Generated by Django 5.1.4 on 2025-01-02 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_weight_week_weight_change_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_weight_loss_percentage_per_week',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(limit_value=-3), django.core.validators.MaxValueValidator(limit_value=-3)]),
        ),
    ]
