# Generated by Django 5.1.4 on 2025-02-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_target_weight_loss_percentage_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight_loss_start_date',
            field=models.DateField(null=True),
        ),
    ]
