# Generated by Django 5.1.4 on 2025-02-18 18:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_weight_loss_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='week_weight_change_kg',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('-6')), django.core.validators.MaxValueValidator(limit_value=Decimal('6'))]),
        ),
        migrations.AlterField(
            model_name='weight',
            name='week_weight_change_percentage',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('-3')), django.core.validators.MaxValueValidator(limit_value=Decimal('3'))]),
        ),
    ]
