# Generated by Django 5.1.6 on 2025-02-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_weight_week_weight_change_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intermediate_loss_target_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
