# Generated by Django 5.1.7 on 2025-03-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_intermediate_loss_target_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='week_weight_change_kg',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='week_weight_change_percentage',
        ),
    ]
