# Generated by Django 5.1.7 on 2025-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_weight_week_weight_change_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight_loss_at_date',
            field=models.DateField(null=True),
        ),
    ]
