# Generated by Django 5.2.4 on 2025-07-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_weight_loss_at_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='authentication_method',
            new_name='authentication_backend',
        ),
    ]
