# Generated by Django 5.2.4 on 2025-08-03 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_authentication_method_user_authentication_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='intermediate_loss_target_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='starting_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(40.0), django.core.validators.MaxValueValidator(250.0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='target_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(40.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
