# Generated by Django 4.2.6 on 2023-10-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weights", "0002_rename_weights_weight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weight",
            options={"ordering": ("-date",)},
        ),
    ]
