# Generated by Django 4.2.7 on 2023-11-14 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("weights", "0003_alter_weight_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height_cm", models.IntegerField()),
                (
                    "starting_weight_kg",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "target_weight_kg",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=2
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
