# Generated by Django 4.2.7 on 2023-11-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weights", "0004_weightuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weightuser",
            name="height_cm",
        ),
        migrations.AddField(
            model_name="weightuser",
            name="height_m",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=3
            ),
            preserve_default=False,
        ),
    ]
