# Generated by Django 4.2.7 on 2023-11-28 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weights", "0005_remove_weightuser_height_cm_weightuser_height_m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weight",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="weights.weightuser",
            ),
        ),
    ]
