# Generated by Django 4.2.7 on 2023-11-29 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weights", "0006_alter_weight_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="weight",
            name="week_weight_change",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(limit_value=-6),
                    django.core.validators.MaxValueValidator(limit_value=6),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="weight",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(limit_value=30)
                ],
            ),
        ),
    ]
