# Generated by Django 4.2.7 on 2023-11-29 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weights", "0007_weight_week_weight_change_alter_weight_weight"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weight",
            old_name="week_weight_change",
            new_name="week_weight_change_kg",
        ),
        migrations.RenameField(
            model_name="weight",
            old_name="weight",
            new_name="weight_kg",
        ),
    ]
