# Generated by Django 4.2.7 on 2023-11-29 08:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "weights",
            "0008_rename_week_weight_change_weight_week_weight_change_kg_and_more",  # noqa: E501
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="weight",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weight_user",
                to="weights.weightuser",
            ),
        ),
        migrations.AlterField(
            model_name="weight",
            name="week_weight_change_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(limit_value=-6),
                    django.core.validators.MaxValueValidator(limit_value=6),
                ],
            ),
        ),
    ]
