# Generated by Django 4.2.7 on 2023-11-29 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "weights",
            "0009_alter_weight_user_alter_weight_week_weight_change_kg",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weight",
            unique_together={("user", "date")},
        ),
    ]
